# Generated by Django 3.2 on 2022-02-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_citydict_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citydict',
            name='add_time',
        ),
    ]
